{
	"version": 1587166913,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/g-sheet0.png",
		"images/sprite-sheet0.png",
		"images/bk-sheet0.png",
		"images/bk-sheet1.png",
		"images/spritefont.png",
		"images/levels.png",
		"images/start-sheet0.png",
		"images/start-sheet1.png",
		"images/timer321.png",
		"images/sprite3-sheet0.png",
		"images/submit-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/options-sheet0.png",
		"images/options-sheet1.png",
		"images/sprite5-sheet0.png",
		"images/levels2.png",
		"media/starlight waltz.m4a",
		"media/starlight waltz.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"play.xml"
	]
}